# Generated by Django 2.2.4 on 2020-06-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
