# Generated by Django 2.2.4 on 2020-06-07 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=300)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('contact_links', models.CharField(max_length=1000)),
                ('about_me', models.TextField(max_length=2000)),
                ('objective', models.CharField(max_length=500)),
                ('degree', models.CharField(max_length=100)),
                ('tenth_school', models.CharField(max_length=500)),
                ('tenth_board', models.CharField(max_length=10)),
                ('tenth_percentage', models.CharField(max_length=10)),
                ('twelfth_school', models.CharField(max_length=500)),
                ('twelfth_board', models.CharField(max_length=10)),
                ('twelfth_percentage', models.CharField(max_length=10)),
                ('university', models.CharField(max_length=500)),
                ('avg_cgpa', models.CharField(max_length=50)),
                ('internship', models.TextField(max_length=2000)),
                ('work_experience', models.TextField(max_length=2000)),
                ('skills', models.TextField(max_length=1000)),
                ('awards_or_certificates', models.TextField(max_length=1000)),
            ],
        ),
    ]
