# Generated by Django 2.2.4 on 2020-06-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='contact_links',
            new_name='portfolio_links',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='awards_or_certificates',
        ),
        migrations.AddField(
            model_name='detail',
            name='field_degree',
            field=models.CharField(default='Field of study', max_length=100),
        ),
    ]
