# Generated by Django 2.2.4 on 2020-06-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200608_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
